backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master

media_folder: "assets/img/uploads"

collections:
  - name: "bolsas"
    label: "bolsas"
    folder: "_bolsas"
    create: true
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Preço", name: "price", widget: "number"}
      - {label: "Imagem", name: "image", widget: "image"}